packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': false
  '@scarf/scarf': true
  bufferutil: true
  core-js-pure: true
  esbuild: true
  keytar: true
  prisma: false
  puppeteer: true
  sharp: true
  workerd: true
