// biome-ignore lint/performance/noBarrelFile: required `@marble/db/schema` export surface
export * from "./api-keys";
export * from "./auth";
export * from "./billing";
export * from "./content";
export * from "./data-transfer";
export * from "./enums";
export * from "./fields";
export * from "./media";
export * from "./relations";
export * from "./taxonomy";
export * from "./usage";
export * from "./webhooks";
export * from "./workspaces";
export { workspace as organization } from "./workspaces";

import { apiKey } from "./api-keys";
import { account, session, user, verification } from "./auth";
import { subscription } from "./billing";
import { post, postToAuthor, postToTag, shareLink } from "./content";
import { exportJob, importItem, importJob } from "./data-transfer";
import {
  apiKeyTypeEnum,
  apiScopeEnum,
  exportFormatEnum,
  exportJobStatusEnum,
  fieldTypeEnum,
  importFormatEnum,
  importItemStatusEnum,
  importJobStatusEnum,
  importSourceEnum,
  mediaTypeEnum,
  payloadFormatEnum,
  planTypeEnum,
  postStatusEnum,
  subscriptionRecurringIntervalEnum,
  subscriptionStatusEnum,
  usageAlertKindEnum,
  usageEventTypeEnum,
  webhookDeliveryStatusEnum,
  workspaceEventActorTypeEnum,
  workspaceEventResourceTypeEnum,
  workspaceEventSourceEnum,
  workspaceEventTypeEnum,
} from "./enums";
import { field, fieldOption, fieldValue } from "./fields";
import { media } from "./media";
import {
  accountRelations,
  apiKeyRelations,
  authorRelations,
  authorSocialRelations,
  categoryRelations,
  exportJobRelations,
  fieldOptionRelations,
  fieldRelations,
  fieldValueRelations,
  importItemRelations,
  importJobRelations,
  invitationRelations,
  mediaRelations,
  memberRelations,
  postRelations,
  postToAuthorRelations,
  postToTagRelations,
  sessionRelations,
  shareLinkRelations,
  subscriptionRelations,
  tagRelations,
  usageAlertRelations,
  usageEventRelations,
  userNotificationPreferencesRelations,
  userRelations,
  verificationRelations,
  webhookDeliveryAttemptRelations,
  webhookDeliveryRelations,
  webhookEndpointRelations,
  workspaceEventRelations,
  workspaceNotificationPreferencesRelations,
  workspaceRelations,
} from "./relations";
import { author, authorSocial, category, tag } from "./taxonomy";
import { usageAlert, usageEvent } from "./usage";
import {
  webhookDelivery,
  webhookDeliveryAttempt,
  webhookEndpoint,
  workspaceEvent,
} from "./webhooks";
import {
  invitation,
  member,
  userNotificationPreferences,
  workspace,
  workspaceNotificationPreferences,
} from "./workspaces";

export const schema = {
  apiKeyTypeEnum,
  apiScopeEnum,
  exportFormatEnum,
  exportJobStatusEnum,
  fieldTypeEnum,
  importFormatEnum,
  importItemStatusEnum,
  importJobStatusEnum,
  importSourceEnum,
  mediaTypeEnum,
  payloadFormatEnum,
  planTypeEnum,
  postStatusEnum,
  subscriptionRecurringIntervalEnum,
  subscriptionStatusEnum,
  usageAlertKindEnum,
  usageEventTypeEnum,
  webhookDeliveryStatusEnum,
  workspaceEventActorTypeEnum,
  workspaceEventResourceTypeEnum,
  workspaceEventSourceEnum,
  workspaceEventTypeEnum,
  workspace,
  user,
  session,
  account,
  verification,
  member,
  invitation,
  userNotificationPreferences,
  workspaceNotificationPreferences,
  subscription,
  author,
  authorSocial,
  category,
  tag,
  post,
  postToTag,
  postToAuthor,
  shareLink,
  media,
  field,
  fieldOption,
  fieldValue,
  apiKey,
  webhookEndpoint,
  workspaceEvent,
  webhookDelivery,
  webhookDeliveryAttempt,
  usageEvent,
  usageAlert,
  exportJob,
  importJob,
  importItem,
  shareLinkRelations,
  postRelations,
  workspaceRelations,
  usageEventRelations,
  authorSocialRelations,
  authorRelations,
  apiKeyRelations,
  userRelations,
  subscriptionRelations,
  fieldRelations,
  fieldOptionRelations,
  fieldValueRelations,
  workspaceNotificationPreferencesRelations,
  memberRelations,
  mediaRelations,
  userNotificationPreferencesRelations,
  workspaceEventRelations,
  webhookDeliveryRelations,
  webhookEndpointRelations,
  webhookDeliveryAttemptRelations,
  usageAlertRelations,
  importItemRelations,
  importJobRelations,
  exportJobRelations,
  categoryRelations,
  tagRelations,
  sessionRelations,
  accountRelations,
  invitationRelations,
  postToTagRelations,
  postToAuthorRelations,
  verificationRelations,
};
